import Foundation

// Generated from Python yfinance.const at build-time for parity.
internal enum YFScreenerConst {
internal static let equityFields: Set<String> = Set([
        "altmanzscoreusingtheaveragestockinformationforaperiod.lasttwelvemonths",
        "avgdailyvol3m",
        "basicepscontinuingoperations.lasttwelvemonths",
        "beta",
        "bookvalueshare.lasttwelvemonths",
        "capitalexpenditure.lasttwelvemonths",
        "cashfromoperations.lasttwelvemonths",
        "cashfromoperations1yrgrowth.lasttwelvemonths",
        "consecutive_years_of_dividend_growth_count",
        "currentratio.lasttwelvemonths",
        "days_to_cover_short.value",
        "dayvolume",
        "dilutedeps1yrgrowth.lasttwelvemonths",
        "dilutedepscontinuingoperations.lasttwelvemonths",
        "ebit.lasttwelvemonths",
        "ebitda.lasttwelvemonths",
        "ebitda1yrgrowth.lasttwelvemonths",
        "ebitdainterestexpense.lasttwelvemonths",
        "ebitdamargin.lasttwelvemonths",
        "ebitinterestexpense.lasttwelvemonths",
        "environmental_score",
        "eodprice",
        "eodvolume",
        "epsgrowth.lasttwelvemonths",
        "esg_score",
        "exchange",
        "fiftytwowkpercentchange",
        "forward_dividend_per_share",
        "forward_dividend_yield",
        "governance_score",
        "grossprofit.lasttwelvemonths",
        "grossprofitmargin.lasttwelvemonths",
        "highest_controversy",
        "industry",
        "intradaymarketcap",
        "intradayprice",
        "intradaypricechange",
        "lastclose52weekhigh.lasttwelvemonths",
        "lastclose52weeklow.lasttwelvemonths",
        "lastclosemarketcap.lasttwelvemonths",
        "lastclosemarketcaptotalrevenue.lasttwelvemonths",
        "lastclosepriceearnings.lasttwelvemonths",
        "lastclosepricetangiblebookvalue.lasttwelvemonths",
        "lastclosetevebit.lasttwelvemonths",
        "lastclosetevebitda.lasttwelvemonths",
        "lastclosetevtotalrevenue.lasttwelvemonths",
        "leveredfreecashflow.lasttwelvemonths",
        "leveredfreecashflow1yrgrowth.lasttwelvemonths",
        "ltdebtequity.lasttwelvemonths",
        "netdebtebitda.lasttwelvemonths",
        "netepsbasic.lasttwelvemonthsnetepsdiluted.lasttwelvemonths",
        "netincome1yrgrowth.lasttwelvemonths",
        "netincomeis.lasttwelvemonths",
        "netincomemargin.lasttwelvemonths",
        "operatingcashflowtocurrentliabilities.lasttwelvemonths",
        "operatingincome.lasttwelvemonths",
        "pctheldinsider",
        "pctheldinst",
        "peer_group",
        "pegratio_5y",
        "peratio.lasttwelvemonths",
        "percentchange",
        "pricebookratio.quarterly",
        "quarterlyrevenuegrowth.quarterly",
        "quickratio.lasttwelvemonths",
        "region",
        "returnonassets.lasttwelvemonths",
        "returnonequity.lasttwelvemonths",
        "returnontotalcapital.lasttwelvemonths",
        "sector",
        "short_interest.value",
        "short_interest_percentage_change.value",
        "short_percentage_of_float.value",
        "short_percentage_of_shares_outstanding.value",
        "social_score",
        "totalassets.lasttwelvemonths",
        "totalcashandshortterminvestments.lasttwelvemonths",
        "totalcommonequity.lasttwelvemonths",
        "totalcommonsharesoutstanding.lasttwelvemonths",
        "totalcurrentassets.lasttwelvemonths",
        "totalcurrentliabilities.lasttwelvemonths",
        "totaldebt.lasttwelvemonths",
        "totaldebtebitda.lasttwelvemonths",
        "totaldebtequity.lasttwelvemonths",
        "totalequity.lasttwelvemonths",
        "totalrevenues.lasttwelvemonths",
        "totalrevenues1yrgrowth.lasttwelvemonths",
        "totalsharesoutstanding",
        "unleveredfreecashflow.lasttwelvemonths",
    ])

internal static let fundFields: Set<String> = Set([
        "annualreturnnavy1categoryrank",
        "categoryname",
        "eodprice",
        "exchange",
        "initialinvestment",
        "intradayprice",
        "intradaypricechange",
        "performanceratingoverall",
        "riskratingoverall",
    ])

internal static let equityValidValues: [String: Set<String>] = [
        "exchange": Set([
            "AMS",
            "AQS",
            "ASE",
            "ASX",
            "ATH",
            "BER",
            "BRU",
            "BSE",
            "BTS",
            "BUD",
            "BUE",
            "BVB",
            "BVC",
            "CAI",
            "CCS",
            "CNQ",
            "CPH",
            "CXI",
            "DOH",
            "DUS",
            "EBS",
            "FKA",
            "FRA",
            "GER",
            "HAM",
            "HEL",
            "HKG",
            "ICE",
            "IOB",
            "ISE",
            "IST",
            "JKT",
            "JNB",
            "JPX",
            "KLS",
            "KOE",
            "KSC",
            "KUW",
            "LIS",
            "LIT",
            "LSE",
            "MCE",
            "MEX",
            "MIL",
            "MUN",
            "NCM",
            "NEO",
            "NGM",
            "NMS",
            "NSI",
            "NYQ",
            "NZE",
            "OEM",
            "OQB",
            "OQX",
            "OSL",
            "PAR",
            "PCX",
            "PHP",
            "PHS",
            "PNK",
            "PRA",
            "RIS",
            "SAO",
            "SAP",
            "SAU",
            "SES",
            "SET",
            "SGO",
            "SHH",
            "SHZ",
            "STO",
            "STU",
            "TAI",
            "TAL",
            "TLV",
            "TOR",
            "TWO",
            "VAN",
            "VIE",
            "WSE",
            "YHD",
        ]),
        "industry": Set([
            "Advertising Agencies",
            "Aerospace & Defense",
            "Agricultural Inputs",
            "Airlines",
            "Airports & Air Services",
            "Aluminum",
            "Apparel Manufacturing",
            "Apparel Retail",
            "Asset Management",
            "Auto & Truck Dealerships",
            "Auto Manufacturers",
            "Auto Parts",
            "Banks—Diversified",
            "Banks—Regional",
            "Beverages—Brewers",
            "Beverages—Non-Alcoholic",
            "Beverages—Wineries & Distilleries",
            "Biotechnology",
            "Broadcasting",
            "Building Materials",
            "Building Products & Equipment",
            "Business Equipment & Supplies",
            "Capital Markets",
            "Chemicals",
            "Coking Coal",
            "Communication Equipment",
            "Computer Hardware",
            "Confectioners",
            "Conglomerates",
            "Consulting Services",
            "Consumer Electronics",
            "Copper",
            "Credit Services",
            "Department Stores",
            "Diagnostics & Research",
            "Discount Stores",
            "Drug Manufacturers—General",
            "Drug Manufacturers—Specialty & Generic",
            "Education & Training Services",
            "Electrical Equipment & Parts",
            "Electronic Components",
            "Electronic Gaming & Multimedia",
            "Electronics & Computer Distribution",
            "Engineering & Construction",
            "Entertainment",
            "Farm & Heavy Construction Machinery",
            "Farm Products",
            "Financial Conglomerates",
            "Financial Data & Stock Exchanges",
            "Food Distribution",
            "Footwear & Accessories",
            "Furnishings, Fixtures & Appliances",
            "Gambling",
            "Gold",
            "Grocery Stores",
            "Health Information Services",
            "Healthcare Plans",
            "Home Improvement Retail",
            "Household & Personal Products",
            "Industrial Distribution",
            "Information Technology Services",
            "Infrastructure Operations",
            "Insurance Brokers",
            "Insurance—Diversified",
            "Insurance—Life",
            "Insurance—Property & Casualty",
            "Insurance—Reinsurance",
            "Insurance—Specialty",
            "Integrated Freight & Logistics",
            "Internet Content & Information",
            "Internet Retail",
            "Leisure",
            "Lodging",
            "Lumber & Wood Production",
            "Luxury Goods",
            "Marine Shipping",
            "Medical Care Facilities",
            "Medical Devices",
            "Medical Distribution",
            "Medical Instruments & Supplies",
            "Metal Fabrication",
            "Mortgage Finance",
            "Oil & Gas Drilling",
            "Oil & Gas E&P",
            "Oil & Gas Equipment & Services",
            "Oil & Gas Integrated",
            "Oil & Gas Midstream",
            "Oil & Gas Refining & Marketing",
            "Other Industrial Metals & Mining",
            "Other Precious Metals & Mining",
            "Packaged Foods",
            "Packaging & Containers",
            "Paper & Paper Products",
            "Personal Services",
            "Pharmaceutical Retailers",
            "Pollution & Treatment Controls",
            "Publishing",
            "REIT—Diversified",
            "REIT—Healthcare Facilities",
            "REIT—Hotel & Motel",
            "REIT—Industrial",
            "REIT—Mortgage",
            "REIT—Office",
            "REIT—Residential",
            "REIT—Retail",
            "REIT—Specialty",
            "Railroads",
            "Real Estate Services",
            "Real Estate—Development",
            "Real Estate—Diversified",
            "Recreational Vehicles",
            "Rental & Leasing Services",
            "Residential Construction",
            "Resorts & Casinos",
            "Restaurants",
            "Scientific & Technical Instruments",
            "Security & Protection Services",
            "Semiconductor Equipment & Materials",
            "Semiconductors",
            "Shell Companies",
            "Silver",
            "Software—Application",
            "Software—Infrastructure",
            "Solar",
            "Specialty Business Services",
            "Specialty Chemicals",
            "Specialty Industrial Machinery",
            "Specialty Retail",
            "Staffing & Employment Services",
            "Steel",
            "Telecom Services",
            "Textile Manufacturing",
            "Thermal Coal",
            "Tobacco",
            "Tools & Accessories",
            "Travel Services",
            "Trucking",
            "Uranium",
            "Utilities—Diversified",
            "Utilities—Independent Power Producers",
            "Utilities—Regulated Electric",
            "Utilities—Regulated Gas",
            "Utilities—Regulated Water",
            "Utilities—Renewable",
            "Waste Management",
        ]),
        "peer_group": Set([
            "Aerospace & Defense",
            "Auto Components",
            "Automobiles",
            "Banks",
            "Building Products",
            "Chemicals",
            "China Fund Aggressive Allocation Fund",
            "China Fund Equity Funds",
            "China Fund QDII Greater China Equity",
            "China Fund QDII Sector Equity",
            "China Fund Sector Equity Financial and Real Estate",
            "Commercial Services",
            "Construction & Engineering",
            "Construction Materials",
            "Consumer Durables",
            "Consumer Services",
            "Containers & Packaging",
            "Diversified Financials",
            "Diversified Metals",
            "EAA CE Global Large-Cap Blend Equity",
            "EAA CE Other",
            "EAA CE Sector Equity Biotechnology",
            "EAA CE UK Large-Cap Equity",
            "EAA CE UK Small-Cap Equity",
            "EAA Fund Asia ex-Japan Equity",
            "EAA Fund China Equity",
            "EAA Fund China Equity - A Shares",
            "EAA Fund Denmark Equity",
            "EAA Fund EUR Aggressive Allocation - Global",
            "EAA Fund EUR Corporate Bond",
            "EAA Fund EUR Moderate Allocation - Global",
            "EAA Fund Emerging Europe ex-Russia Equity",
            "EAA Fund Europe Large-Cap Blend Equity",
            "EAA Fund Eurozone Large-Cap Equity",
            "EAA Fund Germany Equity",
            "EAA Fund Global Emerging Markets Equity",
            "EAA Fund Global Equity Income",
            "EAA Fund Global Flex-Cap Equity",
            "EAA Fund Global Large-Cap Blend Equity",
            "EAA Fund Global Large-Cap Growth Equity",
            "EAA Fund Hong Kong Equity",
            "EAA Fund Japan Large-Cap Equity",
            "EAA Fund Other Bond",
            "EAA Fund Other Equity",
            "EAA Fund RMB Bond - Onshore",
            "EAA Fund Sector Equity Consumer Goods & Services",
            "EAA Fund Sector Equity Financial Services",
            "EAA Fund Sector Equity Industrial Materials",
            "EAA Fund Sector Equity Technology",
            "EAA Fund South Africa & Namibia Equity",
            "EAA Fund Switzerland Equity",
            "EAA Fund US Large-Cap Blend Equity",
            "EAA Fund USD Corporate Bond",
            "Electrical Equipment",
            "Energy Services",
            "Food Products",
            "Food Retailers",
            "Healthcare",
            "Homebuilders",
            "Household Products",
            "India CE Multi-Cap",
            "India Fund Large-Cap",
            "India Fund Sector - Financial Services",
            "Industrial Conglomerates",
            "Insurance",
            "Machinery",
            "Media",
            "Mexico Fund Mexico Equity",
            "Oil & Gas Producers",
            "Paper & Forestry",
            "Pharmaceuticals",
            "Precious Metals",
            "Real Estate",
            "Refiners & Pipelines",
            "Retailing",
            "Semiconductors",
            "Software & Services",
            "Steel",
            "Technology Hardware",
            "Telecommunication Services",
            "Textiles & Apparel",
            "Traders & Distributors",
            "Transportation",
            "Transportation Infrastructure",
            "US CE Convertibles",
            "US CE Options-based",
            "US CE Preferred Stock",
            "US Fund China Region",
            "US Fund Consumer Cyclical",
            "US Fund Diversified Emerging Mkts",
            "US Fund Equity Energy",
            "US Fund Equity Precious Metals",
            "US Fund Financial",
            "US Fund Foreign Large Blend",
            "US Fund Health",
            "US Fund Large Blend",
            "US Fund Large Growth",
            "US Fund Large Value",
            "US Fund Miscellaneous Region",
            "US Fund Natural Resources",
            "US Fund Technology",
            "US Fund Trading--Leveraged Equity",
            "Utilities",
        ]),
        "region": Set([
            "ar",
            "at",
            "au",
            "be",
            "br",
            "ca",
            "ch",
            "cl",
            "cn",
            "co",
            "cz",
            "de",
            "dk",
            "ee",
            "eg",
            "es",
            "fi",
            "fr",
            "gb",
            "gr",
            "hk",
            "hu",
            "id",
            "ie",
            "il",
            "in",
            "is",
            "it",
            "jp",
            "kr",
            "kw",
            "lk",
            "lt",
            "lv",
            "mx",
            "my",
            "nl",
            "no",
            "nz",
            "pe",
            "ph",
            "pk",
            "pl",
            "pt",
            "qa",
            "ro",
            "ru",
            "sa",
            "se",
            "sg",
            "sr",
            "sw",
            "th",
            "tr",
            "tw",
            "us",
            "ve",
            "vn",
            "za",
        ]),
        "sector": Set([
            "Basic Materials",
            "Communication Services",
            "Consumer Cyclical",
            "Consumer Defensive",
            "Energy",
            "Financial Services",
            "Healthcare",
            "Industrials",
            "Real Estate",
            "Technology",
            "Utilities",
        ]),
]

internal static let fundValidValues: [String: Set<String>] = [
        "exchange": Set([
            "NAS",
        ]),
]
}
